export const events = [
    {
        id: "wedding",
        title: "Wedding Collection",
        icon: "💒",
        path: "/collection/event/wedding",
        outfitTypes: [
            "lehenga set",
            "sherwani set",
            "achkan set",
            "pathani",
            "engagement lehenga",
            "reception gown",
            "anarkali",
        ],
    },
    {
        id: "engagement",
        title: "Engagement Collection",
        icon: "💍",
        path: "/collection/event/engagement",
        outfitTypes: [
            "engagement lehenga",
            "anarkali",
            "co ord set",
            "indo western set",
            "kurta jacket",
            "achkan set",
            "lehenga choli",
            "kurti skirt",
            "ethnic jacket",
        ],
    },
    {
        id: "salwar",
        title: "Salwar & Suits",
        icon: "👗",
        path: "/collection/event/salwar",
        outfitTypes: ["salwar suit", "anarkali", "sharara", "kurti skirt", "kurta pajamas"],
    },
    {
        id: "reception",
        title: "Reception & Party Wear",
        icon: "✨",
        path: "/collection/event/reception",
        outfitTypes: [
            "reception gown",
            "lehenga set",
            "saree",
            "indo western set",
            "sherwani set",
            "gown",
            "co ord set",
        ],
    },
];